### ISSUE TITLE
USER STORY: Manage bookings

### ISSUE THREAD

**Issue by KyrianU** [KyrianU/taste-of-africa#10]
As a user, I want to be able to log in and see all my existing reservations

Acceptance criteria:

- [ ] User can navigate to my reservations and have look at their existing bookings
- [ ] Users can see the time, date and reservation number
- [ ] Users can only view their existing reservation
