### ISSUE TITLE
USER STORY: Make a booking

### ISSUE THREAD

**Issue by KyrianU** [KyrianU/taste-of-africa#5]
As a user, I want to be able to fill a booking form in order to make a reservation

Acceptance Criteria:

- [ ] User can choose a date and time for their booking
- [ ] User can choose how many guest for their booking
- [ ] Reservation saved and also visible on their account
