### ISSUE TITLE
USER STORY: User Registration

### ISSUE THREAD

**Issue by KyrianU** [KyrianU/taste-of-africa#6]
As a user, I want to be able to register in order to log in and access my bookings

Acceptance Criteria:

- [ ] User can navigate to the registration page
- [ ] User can input their username and password
- [ ] User will be redirected to home screen after successful sign up
